name: Run Python Script

# This specifies when the workflow should run
on:
  push:
    branches:
      - main  # Triggers on push to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

# Workflow jobs
jobs:
  run-script:
    runs-on: ubuntu-latest  # The operating system to run on

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Sets up Python
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Run Python script
        run: python cloud1.py  # Replace with your script's name
